apiVersion: 1
datasources:
  - name: Tempo
    uid: aishop-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: aishop-loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        tags:
          - key: service.name
            value: service_name
        filterByTraceID: true
        filterBySpanID: false
        customQuery: false
      tracesToMetrics:
        datasourceUid: aishop-prometheus
      serviceMap:
        datasourceUid: aishop-prometheus
      nodeGraph:
        enabled: true
