apiVersion: 1
datasources:
  - name: Tempo
    uid: aishop-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: aishop-prometheus
      serviceMap:
        datasourceUid: aishop-prometheus
      nodeGraph:
        enabled: true
