REDIS_PREFIX = "mall:"

WS_MESSAGE_TOPIC = "message.topic"
WS_MESSAGE_TOPIC_AGENT = "message.topic.agent"
WS_MESSAGE_TOPIC_ADMIN = "message.topic.admin"
WS_MESSAGE_TYPE_AGENT = "agent"
WS_MESSAGE_TYPE_SUPPORT = "support"
TOKEN_COOKIE_NAME = "token"
TOKEN_HEADER_NAME = "token"

REDIS_TOKEN_WEB = f"{REDIS_PREFIX}token:web:"
REDIS_TOKEN_USERID_WEB = f"{REDIS_PREFIX}token:web:userId:"
REDIS_CANCEL_AGENT = f"{REDIS_PREFIX}cancel:agent:message:userId:"
REDIS_PROMPT = f"{REDIS_PREFIX}prompt:"
REDIS_AGENT_CONSULT_PRODUCT = f"{REDIS_PREFIX}agent:consult:product:userId:"
REDIS_AGENT_CONSULT_ACTIVE = f"{REDIS_PREFIX}agent:consult:active:"
REDIS_AGENT_SHOPPING_PROFILE = f"{REDIS_PREFIX}agent:shopping:profile:userId:"
REDIS_AGENT_IMPRESSION_LOG = f"{REDIS_PREFIX}agent:rec:impression:userId:"
REDIS_AGENT_CLICK_LOG = f"{REDIS_PREFIX}agent:rec:click:userId:"
REDIS_AGENT_IMPRESSION_REQUEST = f"{REDIS_PREFIX}agent:rec:impression:request:"
REDIS_AGENT_PENDING_ACTION = f"{REDIS_PREFIX}agent:pending:action:"
REDIS_AGENT_PENDING_MSG = f"{REDIS_PREFIX}agent:pending:msg:userId:"
REDIS_AGENT_SESSION = f"{REDIS_PREFIX}agent:session:"
REDIS_AGENT_SESSION_COMPRESS_LOCK = f"{REDIS_PREFIX}agent:session:compress:lock:"
REDIS_AGENT_HISTORY_CONDENSED = f"{REDIS_PREFIX}agent:history:condensed:userId:"
REDIS_SENSITIVE_WORD_PAYLOAD = f"{REDIS_PREFIX}sensitive:word:payload"
REDIS_WS_USER_HEARTBEAT = f"{REDIS_PREFIX}user:heartBeat:"
REDIS_AGENT_USER_LOCK = f"{REDIS_PREFIX}agent:worker:user-lock:"
REDIS_AGENT_WORKER_HEARTBEAT = f"{REDIS_PREFIX}agent:worker:heartbeat"
REDIS_TOKEN_ADMIN = f"{REDIS_PREFIX}token:admin:"

AGENT_QUEUE_HIGH = "agent.support.high"
AGENT_QUEUE_FAST = "agent.faq.fast"
AGENT_QUEUE_LOW = "agent.shopping.low"
AGENT_QUEUE_DEAD = "agent.tasks.dead"

SUPPORT_STATUS_QUEUED = "QUEUED"
SUPPORT_STATUS_ASSIGNED = "ASSIGNED"
SUPPORT_STATUS_ACTIVE = "ACTIVE"
SUPPORT_STATUS_RESOLVED = "RESOLVED"
SUPPORT_STATUS_CANCELLED = "CANCELLED"

MSG_STATUS_CANCEL = 0
MSG_STATUS_NORMAL = 1
MSG_STATUS_COMPLETE = 2
MSG_STATUS_INTERRUPTED = 3

OUTPUTTING = 0
DONE = 1
ERROR = 2

RRF_K = 60
PRODUCT_RESULT_SIZE = 12
PRODUCT_CANDIDATE_SIZE = 24
SIMILAR_PRODUCT_SIZE = 8

# Requests longer than this have usually spelled out their own intent, so a
# clarifying question would just get in the way.
CLARIFY_MAX_TEXT_LENGTH = 40

# Impression log: capped per-user list, short TTL. Sized for offline CTR
# analysis on an MVP, not for a warehouse.
IMPRESSION_LOG_TTL = 7 * 24 * 60 * 60
IMPRESSION_ATTRIBUTION_TTL = 7 * 24 * 60 * 60
IMPRESSION_LOG_MAX_ENTRIES = 200
IMPRESSION_LOG_MAX_PRODUCTS = 20

PENDING_ACTION_TTL = 30 * 60
CANCEL_FLAG_TTL = 5 * 60
CONSULT_PRODUCT_TTL = 24 * 60 * 60
SHOPPING_PROFILE_TTL = 7 * 24 * 60 * 60
CONSULT_ACTIVE_TTL = 30 * 60
PENDING_MSG_TTL = 5 * 60
REDIS_HEARTBEAT_TTL = 6

ORDER_STATUS_DELETE = -1
PRODUCT_STATUS_ON_SALE = 1

ORDER_STATUS_WAIT_PAYMENT = 0
ORDER_STATUS_PAID = 1
ORDER_STATUS_SHIPPED = 2
ORDER_STATUS_COMPLETED = 3
ORDER_STATUS_CANCELLED = 4
ORDER_STATUS_CLOSED = 5
ORDER_STATUS_REFUNDED = 6
ORDER_STATUS_PARTIALLY_REFUNDED = 7
ORDER_STATUS_WAIT_COMMENT = 8

ORDER_ITEM_STATUS_REFUND = 0
ORDER_ITEM_STATUS_NORMAL = 1

REFUNDABLE_ORDER_STATUSES = frozenset({
    ORDER_STATUS_PAID,
    ORDER_STATUS_SHIPPED,
    ORDER_STATUS_PARTIALLY_REFUNDED,
})

CONFIRM_RECEIPT_ORDER_STATUSES = frozenset({
    ORDER_STATUS_SHIPPED,
    ORDER_STATUS_PARTIALLY_REFUNDED,
})

CANCELLABLE_ORDER_STATUSES = frozenset({
    ORDER_STATUS_WAIT_PAYMENT,
})

REVIEWABLE_ORDER_STATUSES = frozenset({
    ORDER_STATUS_COMPLETED,
    ORDER_STATUS_PARTIALLY_REFUNDED,
})

ORDER_STATUS_NAMES = {
    -1: "已删除",
    0: "待付款",
    1: "已付款,待发货",
    2: "已发货",
    3: "已完成",
    4: "交易取消",
    5: "交易关闭",
    6: "已退款,交易关闭",
    7: "部分退款",
    8: "待评价",
}
